spring:
  application.name: order-service
  cloud:
    function:
      definition: orderStateStoreProcessor;orderProcess;inventoryCheck;shipping;shippedConsumer
    stream:
      bindings:
        orderStateStoreProcessor-in-0.destination: ${spring.application.name}.orderStatus
        orderStateStoreProcessor-out-0.destination: ${spring.application.name}.orderProcess

#       orderProcess function use branch to forward the data to inventoryCheck,shipping and shippedConsumer
#       orderProcess out is not required buz we are using branch to split and forward data to related topics
        orderProcess-in-0.destination: ${spring.application.name}.orderProcess

        inventoryCheck-in-0.destination: ${spring.application.name}.inventoryCheck
        inventoryCheck-out-0.destination: ${spring.application.name}.orderStatus

        shipping-in-0.destination: ${spring.application.name}.shipping
        shipping-out-0.destination: ${spring.application.name}.orderStatus

        shippedConsumer-in-0.destination: ${spring.application.name}.shipped

      kafka:
        bindings:  #SERDES BINDING
          orderStateStoreProcessor-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          orderStateStoreProcessor-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          orderProcess-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          orderProcess-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          inventoryCheck-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          inventoryCheck-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          shipping-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          shipping-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          shippedConsumer-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        streams:
          bindings: # Assigning unique application id to every consumer
            orderStateStoreProcessor-in-0.consumer.configuration.application.id: ${spring.application.name}-orderStateStoreProcessor
            orderProcess-in-0.consumer.configuration.application.id: ${spring.application.name}-orderProcess
            inventoryCheck-in-0.consumer.configuration.application.id: ${spring.application.name}-inventoryCheck
            shipping-in-0.consumer.configuration.application.id: ${spring.application.name}-shipping
            shippedConsumer-in-0.consumer.configuration.application.id: ${spring.application.name}-shipped
          binder:
            brokers: localhost:9092 # just to use it in the service app, Its already 'localhost:9092' by default
            application.id: ${spring.application.name}
            auto-add-partitions: true
            min-partition-count: 6
            state-store-retry:
              max-attempts: 10
              backoff-period: 500
            configuration: # STREAM SERDES BINDING
              application.server: localhost:${server.port} # for InteractiveQueryService to describe itself
              state.dir: state-${spring.application.name}-${server.port} # to give a unique dir name in case you run multiple of this app on the same machine
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000
              auto.offset.reset: latest